### ISSUE TITLE
[Request] Compatibility

### ISSUE THREAD

**Issue by ardittristan** [navisayslisten/AceEditorVTT#1]
Please check for compatibility with other modules that use ace (like not enough npcs) since ace is very prone to breaking if multiple modules use it (ace.config.basePath might break other modules using ace for example)

**Comment by navisayslisten** [comment]
Thanks man. Will do. I'm just seeing if I can standardize importing ace and its dependencies for now. It's very touchy.

**Comment by navisayslisten** [comment]
My forked repo of yours is looking a lot better than this one. But took me a while to understand what it was your code was editing in the first place. UI dev isn't my area of expertise.

**Comment by DrMcCoy** [comment]
The Furnace is no more, but this editor module is still incompatible with at least one of the successor modules, Advanced Macros.

And yeah, even if I disable the Furnace checks, the editor breaks with Advanced Macros enabled.

Is there a way to make them compatible?

**Comment by navisayslisten** [comment]
I'll look into it.

**Comment by navisayslisten** [comment]
Please use VTTMacroEditor instead @DrMcCoy . This project will be closed.

**Comment by DrMcCoy** [comment]
Ah.

Thank you for your service!
